### ISSUE TITLE
Updating sam-template.yaml

### ISSUE THREAD

**Issue by skurtEnd** [logzio/cloudwatch-metrics-helpers#25]
### Describe your question

We have a slightly older version of the `sam-template` yaml file which we used to provision resources in two regions. There was a need of extending to additional regions however, we have faced issue:
![Image](https://github.com/user-attachments/assets/a15be79d-75f1-4ff0-bd39-ba0e06139002)

It seems to be failing to create the resource named `logzioMetricStreamAddTagsLambda` and here's how it's looking:

```
  logzioMetricStreamAddTagsLambda:
    Type: 'AWS::Lambda::Function'
    DependsOn: logzioMetricStream
    Properties:
      Code:
        S3Bucket: !Join [ '-', [logzio-aws-integrations, !Ref regionValue] ]
        S3Key: metric-stream-helpers/tags/1.2.4/function.zip
      FunctionName: !Join [ '-', [ !Ref AWS::StackName, 'tags-func' ] ]
      Handler: main
      Runtime: go1.x
      Role: !GetAtt logzioTagsLambdaRole.Arn
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          AWS_NAMESPACES: !Ref awsNamespaces
          LOGZIO_METRICS_LISTENER: !Ref logzioListener
          LOGZIO_METRICS_TOKEN: !Ref logzioToken
```

Assuming this is the actual line causing issues: `Runtime: go1.x` since AWS has deprecated go 1.x and suggesting to switch to `provided.al2023`

However, we are seeing additional changes such as `Handler: main` now becomes `Handler: bootstrap`

Can you please assist here so that we apply the minimum required changes?

Also, do we have to make a change here?
`S3Key: metric-stream-helpers/tags/1.2.4/function.zip`
